# config/services.yaml

parameters:
    # Ajoutez vos paramètres ici, si nécessaire

services:
    # Default configuration pour les services dans ce fichier
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances
        autoconfigure: true # Enregistre automatiquement les services comme commandes, etc.

    # Ajoute les classes de src/ comme services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

